import type { Config } from "stylelint";

const config: Config = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-standard-scss",
    "stylelint-config-prettier-scss",
  ],
  plugins: ["stylelint-order"],
  rules: {
    "order/properties-order": [
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "display",
      "flex",
      "flex-direction",
      "flex-wrap",
      "justify-content",
      "align-items",
      "grid-template-columns",
      "grid-template-rows",
      "gap",
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "background",
      "background-color",
      "background-image",
      "border",
      "border-radius",
      "color",
      "font-size",
      "font-weight",
      "line-height",
      "opacity",
      "cursor",
      "transition",
    ],

    "scss/at-rule-no-unknown": true,
    "scss/no-global-function-names": true,
    "color-named": "never",
    "no-duplicate-selectors": true,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
  },
};

export default config;
